### ISSUE TITLE
When trying to copy a message, says "Unknown command." (Fabric)

### ISSUE THREAD

**Issue by cybertelx** [HotLava03/chat-macros#1] opened 2020-11-27 19:59 UTC
How to reproduce:
1. Install mod
2. Join a server
3. Click on a message

Mod Version: 1.4.0 (latest)
MC Version: 1.16.3
Fabric API: fabric-api-0.21.0+build.407-1.16

Mods:
Cloth Config 2
Fabric API
AppleSkin
Chat Macros
VoxelMap
Mod Menu
Not Enough Crashes
MaLiLib
Roughly Enough Items
Shulker Box Tooltip
Sodium
ViaFabric
Voyager
Wurst

**Comment by HotLava03** [comment] 2020-12-05 14:42
@cybertelx Thanks for reporting this issue.
Could you please tell me your chatmacros mod settings? (Mods > ChatMacros > Settings)

**Comment by HotLava03** [comment] 2020-12-05 14:57
![image](https://user-images.githubusercontent.com/44071180/101246207-c2f4f980-3709-11eb-8114-fc17ad32f926.png)
I can't reproduce with these settings.
Fabric API is the same as yours (fabric-api-0.21.0+build.407-1.16), Minecraft 1.16.3, MaLiLib 0.10.0-dev.21+arne.1, ModMenu 1.14.6+build.31.
I will test compatibility with your other mods all together, with their latest 1.16.3-compatible versions.

**Comment by HotLava03** [comment] 2020-12-05 15:46
Alright, I found all issues.
Wurst cancels in-game commands, I assume it's because it has its own local commands with the `.` prefix. From the looks of it, it doesn't seem like it's my problem.
ViaFabric seems to cause a HeadlessException with the same steps, which happens when accessing system clipboard. I can't find a cause for this.

Could you please try disable both these mods and see if it works fine?

**Comment by cybertelx** [comment] 2020-12-08 15:10
I disabled them, yes they work! Thank you!

**Comment by HotLava03** [comment] 2020-12-11 20:15
Unfortunately, it looks like I can't solve this right now, as the mod is.
In the future, I have plans to change the way copying to clipboard works, into not using any commands, but for now, as this works based on chat click events which can only run commands by default, I'll have to rely on commands.

It's still very weird, for the fact Wurst doesn't allow other mods to have custom commands. And if it does, something's not right. Maybe what you can do is contact Wurst's developers, as this will affect any mod that has custom commands for sure.

Closing this now. If you do find this to be chat-macros' issue though, please re-open a new issue and explain the cause. Thanks!

**Closed by HotLava03** 2020-12-11 20:15 UTC
Labels: incompatibility
